from __future__ import annotations

from typing import Protocol, TypeAlias


ColorRGB: TypeAlias = tuple[int, int, int]
ColorRGBA: TypeAlias = tuple[int, int, int, int]
ColorValue: TypeAlias = ColorRGB | ColorRGBA
Point: TypeAlias = tuple[float, float] | tuple[int, int]
RectTuple: TypeAlias = tuple[float, float, float, float] | tuple[int, int, int, int]


class SurfaceLike(Protocol):
	def get_width(self) -> int: ...
	def get_height(self) -> int: ...
	def get_size(self) -> tuple[int, int]: ...
	def blit(self, source: "SurfaceLike", dest: Point, area: RectTuple | None = None) -> object: ...
	def fill(self, color: ColorValue) -> object: ...
	def copy(self) -> "SurfaceLike": ...
	def subsurface(self, rect: RectTuple) -> "SurfaceLike": ...
	def set_alpha(self, alpha: int | None) -> None: ...
	def convert_alpha(self) -> "SurfaceLike": ...
	def get_at(self, pos: tuple[int, int]) -> tuple[int, int, int, int]: ...
	def set_at(self, pos: tuple[int, int], color: ColorValue) -> None: ...


class FontLike(Protocol):
	def render(self, text: str, antialias: bool, color: ColorValue) -> SurfaceLike: ...


class MouseLike(Protocol):
	LEFT: int

	def get_position(self) -> tuple[int, int]: ...
	def button_down(self, button: int) -> bool: ...
	def button_pressed(self, button: int) -> bool: ...


class KeyboardLike(Protocol):
	def key_down(self, key: str) -> bool: ...
	def key_pressed(self, key: str) -> bool: ...
